sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: s12345678
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: ''
    database: 10
  wechat:
    appid: 11
    secret: 22
    mchid: 33
    mchSerialNo: 44
    privateKeyFilePath: /Users/szlsay/apiclient_key.pem
    apiV3Key: 55
    weChatPayCertFilePath: /Users/szlsay/wechatpay_66.pem
    notifyUrl: https://77.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://77.r2.cpolar.top/notify/refundSuccess